### ISSUE TITLE
Signal handlers are not re-entrant

### ISSUE THREAD

**Issue by latortuga** [zendesk/racecar#101]
Hi racecar team, love your gem <3

Racecar's binstub does not properly handle signals in my experience. I get this printed in the output when I send Ctrl+C to `bin/racecar MyConsumer`:

```
log writing failed. can't be called from trap context
```

I've encountered unpredictable failures scenarios around sending signals to racecar actually:

- after killing, I get a console prompt as though the process is gone but I still get output printed to my console
- if you press Ctrl+C enough times you can just crash the process (this is likely a race condition)

The reason this happens is because the signal handlers are not re-entrant. The handlers in `runner.rb` call shutdown code directly from within the `trap` block. This code could be called at any time, including before the previous signal is finished being handled. This is prime race condition territory.

Instead, you should consider using a global queue + a "self pipe" to handle signals serially. This is what sidekiq, foreman, unicorn, and I'm sure many others do to handle this problem.

**Comment by dasch** [comment]
Can you whip up a PR for that?
