### ISSUE TITLE
Does racecar supports message headers ?

### ISSUE THREAD

**Issue by aurelien-ldp** [zendesk/racecar#103]
Since 0.11.0, Kafka implemented message headers ( https://cwiki.apache.org/confluence/display/KAFKA/KIP-82+-+Add+Record+Headers#KIP-82-AddRecordHeaders-Status).

It has been implemented in ruby-kafka: https://github.com/zendesk/ruby-kafka/pull/604.

I didn't find any information about headers on the documentation of Racecar, do you have any information ?

Cheers

**Comment by dasch** [comment]
It does – let me update the README.
