### ISSUE TITLE
How to read form beginning every time

### ISSUE THREAD

**Issue by Ronaq13** [zendesk/racecar#104]
I want to make a rake task in which I want my consumer to read from the beginning so that I can process the messages and store them in the database. 

I went through the documentation at [this](https://github.com/zendesk/ruby-kafka#topic-subscriptions) point and got a variable to set. 

But this works only one time, once the consumer read all the messages it commits its position and next time read from there. But in the rake task, I want whenever that task is executed the consumer reads from the beginning. 

I also didn't find any way to manually set the offset of a consumer.

Thanks in advance

**Comment by dasch** [comment]
You can't use Racecar for this, you'll need to drop down to ruby-kafka itself. If you read https://github.com/zendesk/ruby-kafka#consumer-checkpointing, you can see that it's possible to disable automatic checkpointing.
