### ISSUE TITLE
Why is producing from consumers alpha?

### ISSUE THREAD

**Issue by erikbelusic** [zendesk/racecar#113]
1 - What problems have been seen producing from consumers?
2 - Would using delivery boy from a consumer mitigate any issues with the built in producer?

**Comment by dasch** [comment]
It's less about known problems and more about potential unknown problems. The feature just needs to be used in production for a while. I definitely recommend using it, as it's more like beta quality at this point.

**Comment by dasch** [comment]
I've removed the warning from the README. Let me know if you run into any issues.
