### ISSUE TITLE
Do not put current directory in LOAD_PATH

### ISSUE THREAD

**Issue by mainameiz** [zendesk/racecar#114]
Hello everybody!
First of all, thanks for making such a good project. It is a great addition to such a low-level ruby-kafka :)

---
My question...

I have found a strange issue using racecar + [bootsnap](https://github.com/Shopify/bootsnap).

As you may know Bootsnap recursively scans everything in `$LOAD_PATH` and caches all paths to speed up application boot process.

Also I have found that racecar adds current directory to $LOAD_PATH - https://github.com/zendesk/racecar/commit/0849ecc75fb22649e640d26e337d0be53e4d1dd5.

This causes bootsnap to scan every directory in my rails project :) including shared storage linked to `public/uploads`.

So my question: is it necessary to put current directory into `$LOAD_PATH`?

**Comment by mainameiz** [comment]
I also make a PR https://github.com/zendesk/racecar/pull/115

**Comment by dasch** [comment]
It's done in order for `--require` to work, I believe.

**Comment by mainameiz** [comment]
Oh, I understand. May be this can be done without loading current directory to `$LOAD_PATH`?

E.g.

```ruby
        opts.on("-r", "--require STRING", "Require a library before starting the consumer") do |lib|
          begin
            require lib
          rescue LoadError => _exception
            require File.join(Dir.pwd, lib)
          end
        end
```

What do you think?

**Comment by dasch** [comment]
I think that will subtly change how Ruby loads files, which may cause files to be loaded twice. The string passed to `require` is used to check if a file has already been loaded.

**Comment by dasch** [comment]
Does Rails not also put the current dir in the load path? Or is it just `lib/`?

**Comment by dasch** [comment]
I think one way to deal with this would be to only add to the load pass if `--require` has been passed.

**Comment by mainameiz** [comment]
> Does Rails not also put the current dir in the load path? Or is it just lib/?

Yes, just `/lib` is placed in $load_path, but not root directory.

**Comment by dasch** [comment]
It would be a breaking change to change from current dir to `./lib/`, so I don't think that's an option – but if the modification of the load path can be made conditional on one or more `--require` args being passed then all can be happy?

**Comment by mainameiz** [comment]
> I think one way to deal with this would be to only add to the load pass if --require has been passed.

Not quite understand. Do you mean this?

```ruby
        opts.on("-r", "--require STRING", "Require a library before starting the consumer") do |lib|
          begin
            require lib
          rescue LoadError => _exception
            $LOAD_PATH.unshift(Dir.pwd)
            require lib
          end
        end
```

**Comment by mainameiz** [comment]
Or?

```ruby
        opts.on("-r", "--require STRING", "Require a library before starting the consumer") do |lib|
            $LOAD_PATH.unshift(Dir.pwd)
            require lib
        end
```

**Comment by dasch** [comment]
Not quite. More like

```ruby
load_path_modified = false

# ...

        opts.on("-r", "--require STRING", "Require a library before starting the consumer") do |lib|
            $LOAD_PATH.unshift(Dir.pwd) unless load_path_modified
            load_path_modified = true
            require lib
        end
```

**Comment by mainameiz** [comment]
:thinking: why we need `load_path_modified`? Whether Racecar::Cli can be called multiple times?

**Comment by dasch** [comment]
You can require multiple files, e.g. `--require foo --require bar`. The block will be executed each time.

**Comment by mainameiz** [comment]
https://github.com/zendesk/racecar/pull/117
