### ISSUE TITLE
Kubernetes Readiness/Liveness Probes

### ISSUE THREAD

**Issue by wadetandy** [zendesk/racecar#118]
I'm in the midst of rolling out some racecar workers in our Kubernetes cluster, and I'm interested in whether there are any recommendations on implementing [liveness and readiness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/) for K8s deployments.  Readiness seems relatively easily achievable, as one could drop a file in a known location on startup and have the probe check for that file to exist (this also might not be terribly necessary since k8s deploys are done with `Recreate`). 

I'd love some advice on how to go about implementing liveness, though.  We ran into an issue today where a container got stuck [in a loop trying to connect](https://github.com/zendesk/ruby-kafka/blob/93c45a8c531e8b447f1cd9127c8bc6ce8070c0e6/lib/kafka/consumer_group.rb#L54-L60), which was quickly resolved when the container was killed and a new one came up, but we had to manually resolve the issue.

**Comment by dasch** [comment]
Try checking out the new Prometheus metrics in ruby-kafka. I haven’t tried it yet, but perhaps they can be used?

**Comment by breunigs** [comment]
The way we do it (using racecar backed by librdkafka) is roughly this:

```ruby
RacecarSubscriber.attach_to :racecar
```
```ruby
class RacecarSubscriber < ActiveSupport::Subscriber
  def acknowledged_message(evt) # payload: offset, partition
     # store timestamp :last_acknowledged_message
  end

  # when adding a produced message to the queue
  def produce_message(evt) # payload: value, key, topic, create_time
    # store timestamp :last_produced_message
  end

  # full iteration of polling from Kafka and potentially processing/delivering messages
  def main_loop(evt) # payload: consumer_class
    # store timestamp :main_loop
  end
end
```

A simple server as a
