### ISSUE TITLE
Batch processing API

### ISSUE THREAD

**Issue by filiptepper** [zendesk/racecar#12]
We're considering using `racecar` for some of our Kafka consumers, but our use case requires processing whole batches of messages.

Would you be interested in a contribution that would allow that kind of behavior, built on top of `each_batch` method?

**Comment by dasch** [comment]
I've considered how best to add batch processing APIs. Since I'd like to keep things easy for newcomers, I think simply implementing a `process_batch` method rather than `process` method would probably work best – Racecar can detect which method the consumer class implements and act accordingly.

Can you give me more detail on your use case?

**Comment by filiptepper** [comment]
We use Kafka consumers to write data to different data stores, including Amazon's DynamoDB and Elasticsearch. To improve performance, resource usage and costs we batch multiple Kafka messages to one (or more, depending on how many messages consumer receiver) query.

`process_batch` would be my preferred way of processing as well.

Do you think it would possible to easily return a success / failure from `process_batch` to indicate whether consumer offset position should be updated?

**Comment by dasch** [comment]
@filiptepper there's already an implicit indication: if your method raises an exception, the position won't be advanced; if it doesn't, the position _will_ be advanced. This has worked well until now.

**Comment by filiptepper** [comment]
@dasch Perfect!

I've forked to repository to add some basic `process_batch` and test it with our use case. Will get back to you.

**Comment by dasch** [comment]
:+1:

**Comment by dasch** [comment]
Fixed by #17.
