### ISSUE TITLE
Add option to explicitly configure the consumer group of a consumer

### ISSUE THREAD

**Issue by thiamsantos** [zendesk/racecar#138]
As of today we should be really careful when renaming a consumer class because the consumer group is based on the class name. Seems that is possible that the consumer ended up consuming all the topic again because of wrong renaming of a consumer. 

Would be nice to be able to explicitly define the consumer group in each consumer class.

```rb
class UserBanConsumer < Racecar::Consumer
  subscribes_to "user_banned"
  group_id "my_consumer_group"

  def process(message)
    data = JSON.parse(message.value)
    user = User.find(data["user_id"])
    user.banned = true
    user.save!
  end
end
```

As far as I understand, the only way to that today is by passing the additional configuration directly.

```rb
subscribes_to "user_banned", additional_config: { "group.id"  => "my_consumer_group"} 
```

https://github.com/zendesk/racecar/blob/a4bc8018f52297fee574705a69d03105cfbd4787/lib/racecar/consumer_set.rb#L185

Either way, would be nice to have at least a documentation for this alternative. I would be happy to send a PR for it :)

**Comment by dasch** [comment]
You can already configure the group id explicitly: https://github.com/zendesk/racecar/blob/master/README.md#basic-configuration

**Comment by dasch** [comment]
You can even set it directly on the class:

```ruby 
class HelloConsumer < Racecar::Consumer
  self.group_id = “hello”
end
```
