### ISSUE TITLE
 publish messages without to inherited from Racecar::Consumer

### ISSUE THREAD

**Issue by rinaldifonseca** [zendesk/racecar#140]
Is there any way to publish messages without to inherited from Racecar::Consumer ? 
I would like to produce messages from my service objects.
I didn't find, then I created a class like:

class Foo < Racecar::Consumer
  subscribes_to "some-topic"
  
  def publish(message:, topic: , key:)
    produce(JSON.dump(message), topic: topic, key: key)
  end
end

But I get the following error when I try to produce:

[1] pry(main)> Foo.new.publish(message: {foo: "barX"}, topic: "some-topic", key: "key-1")
NoMethodError: undefined method `produce' for nil:NilClass
from /Users/rinaldifonseca/.rvm/gems/ruby-2.1.3/gems/racecar-1.0.0/lib/racecar/consumer.rb:46:in `produce'

**Comment by dasch** [comment]
No, the `produce` method is private. Take a look at [DeliveryBoy](https://github.com/zendesk/delivery_boy) for your use case.

**Comment by dan3lson** [comment]
The [README section on Producers](https://github.com/stringandkey/app-sk-backend/pull/32) should be updated to reflect this. It's misleading.

**Comment by dan3lson** [comment]
The [README section on Producers](https://github.com/zendesk/racecar#producing-messages) should be updated to reflect this. It's misleading.

**Comment by dasch** [comment]
@dan3lson I'm not sure I follow – the `produce` method can be called from within a consumer class instance.
