### ISSUE TITLE
Error when trying to consume an topic

### ISSUE THREAD

**Issue by Kutomore** [zendesk/racecar#141]
HI, so I just followed the docs trying to get this gem running on my project.

```
Racecar.configure do |config|
  # Each config variable can be set using a writer attribute.
  config.ssl_ca_cert = "config/kafka/ca.pem"
  config.ssl_client_cert = "config/kafka/service.cert"
  config.ssl_client_cert_key = "config/kafka/service.key"
end
```
I have setup this configuration to use the certificates needed for consuming, but when I try to start the consumer I get the following error:

`Crashed: ArgumentError: Could not parse PKey: no start line`

These certificates work without an issue when I use them with the base kafka-ruby gem, am I missing something configuration wise?

**Comment by dasch** [comment]
You need to load the contents of those files into strings and pass those in.

**Comment by Kutomore** [comment]
Hi @dasch , thanks for your response and sorry for the delay.

I adjusted my configuration to:
```
Racecar.configure do |config|
  # Each config variable can be set using a writer attribute.
  config.ssl_ca_cert = File.read("engines/store/config/kafka/ca.pem")
  config.ssl_client_cert = File.read("engines/store/config/kafka/service.cert")
  config.ssl_client_cert_key = File.read("engines/store/config/kafka/service.key")
end
```

And it worked flawlessly, thanks.
