### ISSUE TITLE
General Questions about Implementation

### ISSUE THREAD

**Issue by dm123455** [zendesk/racecar#15]
I wanted to go over some questions I have while implementing racecar for ruby kafka. 

1. So say we have one 1 topic and we want to have 2 consumers belonging to one group to act on that topic. 
a. Do we built separate consumer classes subscribing to the same topic? 
b. I see the racecar.yml having the configurations for brokers, client_id  etc, but I would think the group id should be consumer class specific? If yes how do we declare that in the consumer class to tie two consumers into one group?
c. So once we tie the consumers together in a group, racecar will handle assigning them to partitions automatically?

2. Just to confirm we must have separate daemons to run each consumer class?

3. Is the only point we would want to shut down a consumer is when it crashes? 

4. What process supervisor does Zendesk use? Unit, Kubernetes or God?

5. We were looking into Docker/Mesos, do you have any concerns about using those with racecar?

**Comment by dasch** [comment]
> So say we have one 1 topic and we want to have 2 consumers belonging to one group to act on that topic. 
a. Do we built separate consumer classes subscribing to the same topic?

No – you'll use a single consumer class, but start two Racecar processes. You can test it out by running `racecar MyConsumer` in two separate terminal windows.

> b. I see the racecar.yml having the configurations for brokers, client_id  etc, but I would think the group id should be consumer class specific? If yes how do we declare that in the consumer class to tie two consumers into one group?

The group id is automatically computed based on the consumer class name. You can override it if you want to, but it should just work out of the box.

> c. So once we tie the consumers together in a group, racecar will handle assigning them to partitions automatically?

Yes.

> 2. Just to confirm we must have separate daemons to run each consumer class?

Yes.

> 3. Is the only point we would want to shut down a consumer is when it crashes? 

When you need to deploy an update to a consumer, you will need to shut down the old processes first, then start the new version.

> 4. What process supervisor does Zendesk use? Unit, Kubernetes or God?

We use Runit, managed by Chef – but any supervisor would do. Kubernetes would work well.

> 5. We were looking into Docker/Mesos, do you have any concerns about using those with racecar?

That should be fine. Note that you will want to avoid constantly changing the number of consumers in a group, as membership changes are rather disruptive.

**Comment by dm123455** [comment]
Thanks a lot! :)
