### ISSUE TITLE
Group id

### ISSUE THREAD

**Issue by allcentury** [zendesk/racecar#158]
Is there any reason this shouldn't work?

```ruby
irb(main):018:0> class MyConsumer < Racecar::Consumer
irb(main):019:1> end
=> nil
irb(main):020:0> MyConsumer.group_id
=> nil
```

It seems like `group_id` is generated when you start racecar (if the class itself doesn't define it) but is there a reason `group_id` isn't defined on a `Racecar::Consumer`?

Use case:  

Today I needed to rewind a consumer group and had a hard time tracking down what the consumer group id was that racecar was defaulting to.  I eventually found it.

2 quick items:

- Can I PR an update to this log message that includes the group_id https://github.com/zendesk/racecar/blob/9f46be4e096eb6ea0c1c1e9790e11fd0a1ff8f44/lib/racecar/cli.rb#L24
- Can we move `group_id` to be on `Racecar::Consumer` and remove the config option and force users to set it on the class instead?  I'm unclear how this would even work when an application has multiple consumers

**Comment by dasch** [comment]
Maybe the best option would be to allow initializing Racecar without starting it.
