### ISSUE TITLE
Configuration for `min_message_queue_size`?

### ISSUE THREAD

**Issue by tmtrademarked** [zendesk/racecar#161]
Hey, folks! I see that the configuration object supports tuning the `min_message_queue_size` parameter which is mentioned in the README. But it looks like the 1.0.1 release of the library available on RubyGems doesn't actually include this commit.

Is there a plan to release a new version of the 1.0 line that exposes some of these parameters, or will this configuration only be available in the 2+ versions?

**Comment by dasch** [comment]
If you create a backport PR I can review it.
