### ISSUE TITLE
Allow upgrading consumer groups from v1 to v2.

### ISSUE THREAD

**Issue by dasch** [zendesk/racecar#170]
In order to upgrade existing consumer groups from v1 to v2 without needing to reset their position, we need to have some kind of mapping from the old group protocol to the new.

One possible idea is to do this in the v1 series, with the upgrade happening automatically to match the librdkafka format. Then an upgrade from that to v2 would be seamless.

**Comment by dasch** [comment]
@thijsc do you think this would be feasible? I'm unfamiliar with the librdkafka group protocol – does it match the Java version?

**Comment by thijsc** [comment]
There is some documentation here: https://github.com/edenhill/librdkafka/wiki/Manually-setting-the-consumer-start-offset

It's possible to specify the offsets when using `assign` on a consumer. So I think one could get the partition assignment plus offsets from the old consumer, and set these on the new one?

**Comment by dasch** [comment]
I don't know if it's possible to read from the old protocol and write to the new one. I think the approach would have to be a protocol that can read either version, but always writes the new one.

**Comment by dasch** [comment]
Do you know the "name" of the protocol in librdkafka? (the one passed to `JoinGroup`)

**Comment by thijsc** [comment]
I'm not sure actually, `rdkafka` implements the high level consumer API. Had a read through the docs and didn't find information on the specific name of the protocol it uses.

Does racecar currently use the high level consumer already? Or the simple one?

**Comment by dasch** [comment]
Only the high level one. The protocol name and specifics are probably buried in the code base. But I imagine that rdkafka is compatible with the Java library.

**Comment by thijsc** [comment]
In that case, I would expect it to be compatible. Afaik the brokers handle storage of the consumer groups and this would work in a similar manner for different clients. Would be good to verify.

**Comment by Adithya-copart** [comment]
> Do you know the "name" of the protocol in librdkafka? (the one passed to JoinGroup)


@dasch Will these help in any way? 
[JoinGroup API key](https://github.com/edenhill/librdkafka/blob/b50e247b77864c595569f7f7e9ec8dde63258210/src/rdkafka_proto.h#L64), [JoinGroup request](https://github.com/edenhill/librdkafka/blob/dae934a831d9808e0166604c45b57d2cc6898ab5/src/rdkafka_request.c#L1358-L1464)

**Comment by dasch** [comment]
Went digging – I think the protocol name is `consumer`, based on https://github.com/edenhill/librdkafka/blob/cedb2917396ddb02a853330adf5030506abdebf3/src/rdkafka_conf.c#L938-L941

**Comment by dasch** [comment]
We need to know the exact format of the binary component, though, in order to safely write such that rdkafka can read.

**Comment by Adithya-copart** [comment]
I think we can add a proxy server and log the requests if it is part of the request. WDYT?

https://github.com/jruby/jruby/issues/6078#issuecomment-606726349

**Comment by Adithya-copart** [comment]
The InconsistentGroupProtocol protocol is thrown while using the same [Api version](https://github.com/zendesk/ruby-kafka/blob/0a07531e3a4214a0f8b8b023fa1eff479c535d3f/lib/kafka/protocol/join_group_request.rb#L25-L27) and roundrobin partition assignment strategy in rdkafka and racecar consumers.

There is a difference in the protocol metadata sent by racecar and librdkafka: [ruby-kafka](https://github.com/zendesk/ruby-kafka/blob/0a07531e3a4214a0f8b8b023fa1eff479c535d3f/lib/kafka/protocol/join_group_request.rb#L40-L43) vs [rdkafka](https://github.com/edenhill/librdkafka/blob/f665358d503284f1e0192df09d1cd5b2515bb8b7/src/rdkafka_request.c#L1403-L1413). The exact metadata sent by librdkafka can be inspected by adding some logging statements to librdkafka and compiling it from the source and linking it in rdkafka-ruby.

@dasch Would racecar consumers using rdkafka need to use a new group id if the deployment strategy ensures that all existing consumers exit the group before the new consumers are added?

**Comment by dasch** [comment]
> The InconsistentGroupProtocol error is thrown while using the same [Api version](https://github.com/zendesk/ruby-kafka/blob/0a07531e3a4214a0f8b8b023fa1eff479c535d3f/lib/kafka/protocol/join_group_request.rb#L25-L27) and roundrobin partition assignment strategy in rdkafka and racecar consumers.
> 
> There is a difference in the protocol metadata sent by racecar and librdkafka: [ruby-kafka](https://github.com/zendesk/ruby-kafka/blob/0a07531e3a4214a0f8b8b023fa1eff479c535d3f/lib/kafka/protocol/join_group_request.rb#L40-L43) vs [rdkafka](https://github.com/edenhill/librdkafka/blob/f665358d503284f1e0192df09d1cd5b2515bb8b7/src/rdkafka_request.c#L1403-L1413). The exact metadata sent by librdkafka can be inspected by adding some logging statements to librdkafka and compiling it from the source and linking it in rdkafka-ruby.

:+1:

> @dasch Would racecar consumers upgrading to rdkafka need to use a new group id if the deployment strategy ensures that all existing consumers exit the group before the new consumers join?

I'm not sure. I would _guess_ that as long as all members leave the group first, then the protocol name can be changed for a new group epoch. But it could be that the broker disallows that for some reason.

**Comment by Adithya-copart** [comment]
@dasch The broker did allow the same group name when I switched from racecar v1 to rdkafka-ruby consumers as long as the old v1 consumers exit the group before the rdkafka consumers start.

I think users who do not use any form of rolling deployments can upgrade to racecar v2 using the same group without any changes other than a gem update. To use a rolling deployment, the process outlined in https://github.com/zendesk/racecar/issues/152 with a new group id and offset updates is to be followed.

I don't think investigating further into the protocol metadata differences in rdkafka and ruby-kafka is needed to close this issue as any changes to the `ruby-kafka` metadata to match rdkafka will result in a `InconsistentGroupProtocol` error as well.

**Test setup: [gist](https://gist.github.com/Adithya-copart/4493f900bf8f58cdaf6ba4bc95aeb1de)** 
1. Kafka/Zookeeper using [docker compose from rdkafka-ruby](https://github.com/appsignal/rdkafka-ruby/blob/master/docker-compose.yml)
2. Rdkafka producer publishing messages to a test topic with 25 partitions.
3. Racecar v1 consumer using a group id subscribed to this test topic.
4. Shutdown racecar v1 consumers.
5. Spawn rdkafka consumers using the same group id and verify the offsets.

[rdkafka debug logs](https://gist.github.com/Adithya-copart/ce6584ff636007719417d24edd59f6b9)

**Comment by dasch** [comment]
@Adithya-copart thank you! I'll update the README to document that.
