### ISSUE TITLE
Memory leaks after consumers are not properly "closed" when the broker disconnects from them

### ISSUE THREAD

**Issue by Hammadk** [zendesk/racecar#194]
First, thanks for maintaining this lovely gem. After upgrading from Racecar `1.1.0` to  `2.0.0`, we noticed that our Kafka consumers were consistently leaking memory and eventually getting killed because out-of-memory errors. We have identified the root cause.

#### Problem

All of these memory leaks start after a broker disconnects from our consumer:

* [Racecar::ConsumerSet#poll](https://github.com/zendesk/racecar/blob/d095104096ee62894a3d2bd47b11821f1b43abee/lib/racecar/consumer_set.rb#L18-L24) calls [RdKafka::Consumer#poll](https://github.com/appsignal/rdkafka-ruby/blob/532afaa12aab6341bf4410324dee90055d9db1b6/lib/rdkafka/consumer.rb#L421-L442). After a broker disconnects, `RdKafka::Consumer#poll` raises `Local: Broker transport failure (transport)`, which means that this RdKafka error has code `-195` (Rdkafka::RdkafkaError.new(-195))
* Racecar attempts to retry this error but it treats [transport failure errors](https://github.com/zendesk/racecar/blob/d095104096ee62894a3d2bd47b11821f1b43abee/lib/racecar/consumer_set.rb#L33-L35) differently than other errors
* [Racecar::ConsumerSet#reset_current_consumer](https://github.com/zendesk/racecar/blob/d095104096ee62894a3d2bd47b11821f1b43abee/lib/racecar/consumer_set.rb#L144-L146) is called and it removes a reference of the effected consumer from the array of consumers with `@consumers[@consumer_id_iterator.peek] = nil`. 

This only removes the reference but we need to [close](https://github.com/appsignal/rdkafka-ruby/blob/main/lib/rdkafka/consumer.rb#L22-L29) the consumer first by calling `RdKafka::Consumer#close`. If they are not closed and just discarded, a [new thread is created under the hood](https://user-images.githubusercontent.com/129764/95362626-580b7b80-089c-11eb-9671-35c652a7ca4e.png) when ConsumerSet creates a new RdKafka consumer.

#### Proposed Solution

Update [Racecar::ConsumerSet#reset_current_consumer](https://github.com/zendesk/racecar/blob/d095104096ee62894a3d2bd47b11821f1b43abee/lib/racecar/consumer_set.rb#L144-L146) so it closes the RdKafka consumer. This is the solution that we implemented in our local patch.

``` ruby
def reset_current_consumer
  current_consumer_id = @consumer_id_iterator.peek
  consumer = @consumers[current_consumer_id]
  consumer.close unless consumer.nil?
  @consumers[current_consumer_id] = nil
end
```

I am happy to write up a PR for this if you'd like.

**Comment by dasch** [comment]
Can you submit that as a PR? :heart:
