### ISSUE TITLE
KingKonf::ConfigError: unknown environment variable RACECAR_SSL_CA_CERTS_FROM_SYSTEM

### ISSUE THREAD

**Issue by mrlevitas** [zendesk/racecar#200]
after upgrading to racecar 2.1.0 , I received this error:
```
KingKonf::ConfigError: unknown environment variable RACECAR_SSL_CA_CERTS_FROM_SYSTEM
```

We rely on this configuration but the consumer won't boot with it.

**Comment by dasch** [comment]
What version were you upgrading from?

**Comment by mrlevitas** [comment]
1.0.1

**Comment by dasch** [comment]
The underlying Kafka client library has been swapped in v2, can you try and see if your app works if you don't set that env var? It could have been a necessity only with the old library.

**Comment by mrlevitas** [comment]
I might not be able to in the near future since the ssl config is only necessary for our production deployment and we'll probably stick with v1 until we have tested v2 better outside of production.  If we do get a chance, I'll report back.

**Comment by mrlevitas** [comment]
Removing `RACECAR_SSL_CA_CERTS_FROM_SYSTEM` env var did allow the consumer to boot but it did not consume anything from the kafka topic. I'm assuming this is due to ssl issue but I'm not sure how to confirm. 
Using same code but racecar v1 does work however.

**Comment by deepredsky** [comment]
In racecar 2.x, ssl settings can be configured using this documentation

https://github.com/zendesk/racecar/blob/meqif/liveness-probe/README.md#ssl-encryption-authentication--authorization
