### ISSUE TITLE
"Broker: Not coordinator for group" errors never recover

### ISSUE THREAD

**Issue by ellimist** [zendesk/racecar#208]
We've recently seen a few errors in production. The error we see is `Broker: Not coordinator for group`.
After this error gets thrown by our consumers, they... never recover and no messages get processed afterwards.

We've been running consumers with this configuration for quite a while, but we started seeing these issues only recently.

Any guidance?
Thanks a lot

**Comment by ellimist** [comment]
Could this fix our issue? https://github.com/zendesk/racecar/pull/209

**Comment by dasch** [comment]
@thijsc this looks more like a problem in rdkafka-ruby or perhaps librdkafka? Should this be handled in Racecar at all in your opinion?

As far as I understand, the "group coordinator" is the Kafka broker assigned to coordinate a specific consumer group. The group coordinator role for a group may be reassigned to another broker for various reasons, in which case the group members likely need to rejoin or resync. But shouldn't this happen transparently in rdkafka?

**Comment by dasch** [comment]
Can you try to see if #219 resolves this issue?

**Comment by deepredsky** [comment]
Fixed in https://github.com/zendesk/racecar/pull/219
