### ISSUE TITLE
Request: Datadog metric documentation

### ISSUE THREAD

**Issue by thrgamon** [zendesk/racecar#220]
Hey!

Loving the library, made is really easy to get up and running consuming from Kafka. One request, is it possible to get some more documentation about the metrics that are reported to Datadog and what they represent?

Many thanks, 

Tom

**Comment by dasch** [comment]
Hi @thrgamon! I won't have time to work on this myself, but if you were to take lead on listing out all the metrics in e.g. the README, then I can help with any questions you might have.

**Comment by dasch** [comment]
@thrgamon BTW, can you try downloading the JSON file from #224 and importing into a new Datadog dashboard and report if that works? The import/export functionality in Datadog should really make this simpler to get started with.

**Comment by thrgamon** [comment]
Hey! I tried importing the dashboard and it works great! That will be really helpful for someone starting from scratch next time. Unfortunately I similarly don't have time to list out all the metrics, but I think we have figured out the ones that we need (or at least the ones that are indicative of good/bad behaviour).
