### ISSUE TITLE
How to commit offset manually?

### ISSUE THREAD

**Issue by filiptepper** [zendesk/racecar#25]
Is there a way to commit offset manually from Consumer?

I don't want any automated offset committing for one particular case.

**Comment by dasch** [comment]
I think that falls far outside the intended niche for Racecar :)

In this case, using raw ruby-kafka for that use case would be the best approach.

**Comment by filiptepper** [comment]
Fair enough.

I'll see how easy would that be to introduce it and if it doesn't bring in too many changes I might end up submitting a PR.

Thanks!
