### ISSUE TITLE
Add required_ruby_version to gemspec? 2.3.0 release is broken on Ruby < 2.5

### ISSUE THREAD

**Issue by ivoanjo** [zendesk/racecar#252]
Hey there! 👋 

I just noticed that the recently-released version 2.3.0 uses the rescue-inside-a-block syntax that was added on Ruby 2.5.

```ruby
$ ruby -v && ruby -e "[].each do; rescue; end"
ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-darwin19]
$ ruby -v && ruby -e "[].each do; rescue; end"
ruby 2.4.10p364 (2020-03-31 revision 67879) [x86_64-darwin19]
-e:1: syntax error, unexpected keyword_rescue, expecting keyword_end
[].each do; rescue; end
                  ^
```

This can be observed by running the test suite on Ruby 2.4:

```ruby
$ bundle exec rake
rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

An error occurred while loading spec_helper.
Failure/Error: require "racecar/consumer"

SyntaxError:
  /racecar/lib/racecar/consumer.rb:76: syntax error, unexpected keyword_rescue, expecting keyword_end
            rescue Rdkafka::AbstractHandle::Wait
                  ^
  /racecar/lib/racecar/consumer.rb:76: syntax error, unexpected =>
  actHandle::WaitTimeoutError => e
                                ^
  /racecar/lib/racecar/consumer.rb:83: syntax error, unexpected keyword_rescue, expecting keyword_end
            rescue Rdkafka::RdkafkaError => e
                  ^
  /racecar/lib/racecar/consumer.rb:83: syntax error, unexpected =>
  escue Rdkafka::RdkafkaError => e
                                ^
  /racecar/lib/racecar/consumer.rb:123: syntax error, unexpected keyword_end, expecting end-of-input
    end
       ^
# ./lib/racecar.rb:7:in `require'
# ./lib/racecar.rb:7:in `<top (required)>'
# ./spec/spec_helper.rb:4:in `require'
# ./spec/spec_helper.rb:4:in `<top (required)>'
No examples found.
No examples found.


Finished in 0.00004 seconds (files took 0.1608 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Finished in 0.00004 seconds (files took 0.1608 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

I'd like to request the addition of [`required_ruby_version = '>= 2.5'` to the gemspec](https://guides.rubygems.org/specification-reference/#required_ruby_version), thus enabling rubygems to avoid using this newer version on older Rubies.

Let me know if you'd like me open a PR with the change, I'd be glad to 😄 

Additionally, it'd be extra nice if you yanked version 2.3.0 and released a 2.3.1 with this change, thus allowing older Rubies to never try to pick version 2.3.0 😉 

Thanks, and have an awesome day!

P.s.: For context, I work at @Datadog our Ruby APM gem [`ddtrace`](https://github.com/DataDog/dd-trace-rb), which also supports integrating with `racecar`, and our CI runs regularly with older Rubies as well, as we have customers still using them 🚀

**Comment by dasch** [comment]
Please open a PR :D

**Comment by dasch** [comment]
And sorry for the late response, I've been on vacation.

**Comment by ivoanjo** [comment]
@dasch done! #256 

> And sorry for the late response, I've been on vacation.

What is this vacation you speak of? Is there life outside my flat? What does it look like? 👀
