### ISSUE TITLE
Integrating Confluent kafka with racecar

### ISSUE THREAD

**Issue by srikanthreddy919** [zendesk/racecar#254]
I have tried to implement Confluent Kafka with racecar with SASL authentication but I am getting messages in Different format
#<Racecar::Message:0x00007ffa15b08be8 @rdkafka_message=#<Rdkafka::Consumer::Message:0x00007ffa15b09ea8 @topic="dv1.aws-use1.align.fct.doctor.v1", @Partition=5, @payload="{"count":0}", @key="alice", @offset=85, @timestamp=2021-07-09 16:26:18 +0530, @headers={}>, @retries_count=0>

Please suggest any idea and solution

**Comment by xiaoronglv** [comment]
Hi @srikanthreddy919 

Have you fixed this issue?

I have the same issue too.

**Comment by xiaoronglv** [comment]
Hi @srikanthreddy919 

here is the workaround to connect confluent kafka.

```
config = {
  :"bootstrap.servers" => "your-kafka.us-west-2.aws.confluent.cloud:9092",
  :"group.id" => "ruby-test",
  :"security.protocol" => "SASL_SSL",
  :"sasl.mechanism" => "PLAIN",
  :"sasl.username" => 'your username',
  :"sasl.password" => 'your password'

}
consumer = Rdkafka::Config.new(config).consumer
consumer.subscribe("core.onboarding.employees")

consumer.each do |message|
  puts "Message received: #{message}"
end
```
