### ISSUE TITLE
No such configuration property "enable.ssl.certificate.verification"

### ISSUE THREAD

**Issue by goyal** [zendesk/racecar#255]
Hello.
I am following the steps described in the readme to setup a racecar consumer but when running the consumer using `racecar MyConsumer` I keep getting the error that is mentioned in the title. I am not doing anything special other than what is described in the readme.

Even when I run the following command, I still get the same error.
`racecarctl produce -v anshul -t topic1`

The exact stack trace is:
```
Rdkafka::Config::ConfigError: No such configuration property: "enable.ssl.certificate.verification"
/rdkafka-0.8.1/lib/rdkafka/config.rb:186:in `block (2 levels) in native_config'
/rdkafka-0.8.1/lib/rdkafka/config.rb:176:in `each'
/rdkafka-0.8.1/lib/rdkafka/config.rb:176:in `block in native_config' <internal:kernel>:90:in `tap'
/rdkafka/config.rb:174:in `native_config'
/rdkafka/config.rb:138:in `producer'
/racecar/runner.rb:138:in `producer'
/racecar/runner.rb:94:in `ensure in run'
/racecar/runner.rb:94:in `run'
/racecar.rb:60:in `run'
/racecar/cli.rb:62:in `run'
/racecar/cli.rb:13:in `main'
```
 
Racecar version 2.3.0 
Ruby version 3.0.0
Platform: OSX 11.4
Running within rails application

I have a local kafka cluster setup. I tried running examples directly from `librdkafka` and I am able to produce/consume messages using my local kafka cluster. That brings me to the fact that I am not configuring something right when using racecar. I did check in [configuration.md](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) that `enable.ssl.certificate.verification` property exist for both producer and consumer. And my `security.protocol` is set to default value which is `plaintext`. 

Is there anything that I am doing wrong or missing a configuration? Any help is appreciated.
Please let me know if I can provide any other relevant information.

Anshul

**Comment by dasch** [comment]
Can you try updating your version of librdkafka? It looks to me like the configuration setting isn't present in the version you're using. And please report back what version _did_ work, as I need to set that as a minimum requirement.

**Comment by goyal** [comment]
I solved my problem by directly using `rdkafka-ruby (0.8.1)` which I believe installed librdkafka v1.4.0 as per [version.rb](https://github.com/appsignal/rdkafka-ruby/blob/main/lib/rdkafka/version.rb).

Still not sure why racecar was giving me that error but when directly using `rdkafka-ruby` the error was not there. I did not investigate any further.

**Comment by deepredsky** [comment]
closing as resolved in newer version of rdkafka-ruby and racecar. Please reopen if the problem exists in newer versions as well
