### ISSUE TITLE
Support for producing Kafka messages

### ISSUE THREAD

**Issue by dasch** [zendesk/racecar#29]
A lot of our use cases are centered around _transforming_ streams of Kafka messages and writing them back to another topic, typically enriched with data from our Rails app. Currently, Racecar provides no direct support for producing messages. Adding direct support would allow the delivery of messages to be optimized.

**Comment by aviflax** [comment]
@dasch [DeliveryBoy](https://github.com/zendesk/delivery_boy) is the library that Zendesk has released for producing to Kafka. You can combine them together to do stream processing, or you can use [ruby-kafka](https://github.com/zendesk/ruby-kafka) which is the more flexible, more powerful, lower-level library that’s the foundation for them both. HTH!

**Comment by dasch** [comment]
Thank you! I'm the author of both libraries, so I'm aware of that 😁 

I was thinking about an integrated solution that coupled the delivery step to the batch processing of Racecar.

**Comment by aviflax** [comment]
Doh! Sorry about that! I guess I just wasn’t paying attention 🤷‍♂️

In that case, BTW, +1! Just today I put together an example of doing stream processing with ruby-kafka — I couldn’t figure out how to use Racecar in a script, outside of Rails — and some kind of built-in simple stream processing feature would be excellent for beginners!

Cheers!

**Comment by webandtech** [comment]
@dasch We also do this. I created a PR. Hope it's useful!
