### ISSUE TITLE
How to do a quick health check

### ISSUE THREAD

**Issue by bragboy** [zendesk/racecar#317]
Hello,

Is there a simple command to check whether the kafka connection is all good without doing any writes/reads like producing/consuming messages. A simple example could be to get the topics count. If it returns a number greater than 0, I can assert that my configuration and connection/handshake to kafka is good.

I can see Racecar uses rdkafka under the hood. So, if i can use a simple command to vet that configuration is good, it would be great. Thank you

**Comment by deepredsky** [comment]
Yeah racecar v2 is using rdkafka-ruby under the hood. So you can reach in to the underlying library to do something. Here is a quick example:

```ruby
    config = { "bootstrap.servers" => "localhost:9092" } # add other config
    native_config = Rdkafka::Config.new(config).send(:native_config) # priv method
    native_kafka = kafka_config.send(:native_kafka, native_config, :rd_kafka_consumer)

    # do whatever with native_kafka, like get the topics count
    kafka_topic_names = Rdkafka::Metadata
                        .new(native_kafka, nil)
                        .topics.count
```

Note that this is reaching in to private methods, so it's possible the interface changes, i hope you get the idea though

**Comment by bragboy** [comment]
Thank you, I did something similar long back, forgot to update it here. 

```ruby
  config = { "bootstrap.servers" => ENV['KAFKA_BROKERS'] }
  if ENV['SECURITY_PROTOCOL'] == 'SSL'
    config.merge!({
      "security.protocol" => "SSL",
      "ssl.certificate.location" => ENV['SSL_CLIENT_CERT_FILE_PATH'],
      "ssl.key.location" => ENV['SSL_CLIENT_CERT_KEY_FILE_PATH'],
      "ssl.key.password" => ENV['SSL_CLIENT_CERT_KEY_PASSWORD']
    })
  end
  native_kafka = Rdkafka::Config.new(config).consumer.instance_variable_get('@native_kafka')
  topics = Rdkafka::Metadata.new(native_kafka).topics.count
  puts "Kafka connection successful. Found topics: #{topics}"
```
