### ISSUE TITLE
Feature request: Connection error handling

### ISSUE THREAD

**Issue by Paxa** [zendesk/racecar#32]
Currently racecar will not call error handler when can not connect to kafka (dns error, host not reachable, open connection error, etc...)

Temporary monkey patch:
```ruby
Racecar::Runner.class_eval do
  alias_method :run_origin, :run

  def run
    run_origin
  rescue Kafka::ConnectionError => error
    config.error_handler.call(error)
    raise error
  end
end
```

**Comment by dasch** [comment]
Do you have a monitoring solution set up in addition to your exception tracker? Connection errors are not exceptional in Kafka, so typically you want to use metrics based alerts rather than exception trackers.

**Comment by Paxa** [comment]
> Do you have a monitoring solution set up in addition to your exception tracker?

Not yet, still thinking how to make it right. The only option I can think of is detecting if process/container exit with error code too often

> Connection errors are not exceptional in Kafka

I got some kafka related errors too, e.g. `Kafka::NoPartitionsAssignedError`, it can connect to port on remote server, but can not start receiving data

**Comment by mensfeld** [comment]
@paxa the no partition error occurs when you have more consumers than partitions in a topic.

**Comment by dasch** [comment]
I would recommend using e.g. Datadog or Librato with Statsd to track metrics. Connection errors is one metric published by ruby-kafka.

**Comment by Paxa** [comment]
@dasch Thank you!
