### ISSUE TITLE
Undefined method `produce_sync' for Racecar:Module

### ISSUE THREAD

**Issue by cooljacob204** [zendesk/racecar#343]
Hey Racecar peeps,

I'm following the https://github.com/zendesk/racecar#standalone-producer and it seems like produce_async is undefined.

I'm on Rails 7.0.4.3, Ruby 3.1.4.

Gemfile lock info for Racecar:

```
    racecar (2.8.2)
      king_konf (~> 1.0.0)
      rdkafka (~> 0.12.0)
```

```
[2] pry(main)> ls Racecar
constants:
  Config       ConsumerSet          Instrumenter          NullInstrumenter  Runner
  ConfigError  ErroneousStateError  Message               ParallelRunner    VERSION
  Consumer     Error                MessageDeliveryError  Pause
Racecar.methods: config  config=  configure  instrumenter  logger  logger=  run
[3] pry(main)> Racecar.produce_sync
NoMethodError: undefined method `produce_sync' for Racecar:Module
from (pry):3:in `__pry__'
```

**Comment by cooljacob204** [comment]
This appears to be due to my racecar version being 2.8.2 instead of the beta version.

**Comment by JoLou123** [comment]
Hey @cooljacob204 I'm facing the same issue, I have the gem defined in my Gemfile as `gem 'racecar'`. How did you set the gem to the beta version?
