### ISSUE TITLE
ActiveSupport::Logger.broadcast dropped in Rails 7.1

### ISSUE THREAD

**Issue by zubin** [zendesk/racecar#356]
After upgrading to Rails 7.1, starting a consumers fails with the following:

```
=> Detected Rails, booting application...
=> Crashed: NoMethodError: undefined method `broadcast' for ActiveSupport::Logger:Class
[...]racecar-2.9.0/lib/racecar/rails_config_file_loader.rb:30:in `load!'
```

Is a fix in the pipeline? If not I'll make a PR shortly.

**Comment by gkosmo** [comment]
I'm curious as to why this PR was closed ( I would have liked that fix :grin:  )
