### ISSUE TITLE
404 librdkafka

### ISSUE THREAD

**Issue by jcoyne** [zendesk/racecar#379]
Racecar 2.11.0, which is the latest released version depends on rdkafka ~> 0.15.0.  This resolves to 0.15.1, which seems to be broken in Ruby 3.3.4.  
https://github.com/sul-dlss/purl-fetcher/actions/runs/9878069566/job/27281152384

**Comment by mensfeld** [comment]
not true. This is the reason: https://github.com/karafka/rdkafka-ruby/issues/465

PLEASE GIVE ME SOME TIME. I am fixing this and mitigating also in rdkafka version used by racecar

**Comment by jcoyne** [comment]
Thanks @mensfeld I just saw that issue and was coming to post that here.

**Comment by mensfeld** [comment]
@jcoyne youcan close this. I released needed patches.
