### ISSUE TITLE
Documentation should mention configuration through Ruby files

### ISSUE THREAD

**Issue by mstahl** [zendesk/racecar#48]
I was having a problem where I needed one of the keys for the Racecar config to be the result of some computation (writing the CA certs to a file temporarily then reading them in that way; sort of an atypical configuration), and I saw in the code that Racecar loads configs from `config/racecar.rb` after loading `config/racecar.yml`, which allowed me to proceed.

This was super useful and I would never have known it was there if I'd only gone by the documentation. I recommend adding a mention of it to the README for others who may be in the same boat.

**Comment by dasch** [comment]
Described the API in https://github.com/zendesk/racecar/commit/e40f8bedb5c2b17310e26535394935d10d74acce.
