### ISSUE TITLE
3.8.0 don't have support for sasl scram ?

### ISSUE THREAD

**Issue by FlorianDoublet** [zendesk/racecar#68]
Hello, 

Five days ago you updated racecar to 3.8.0 and adding ruby-kafka 0.5 in dependencies, with sasl scram feature.

I has updated racecar to version 3.8.0 via bundle update, but it still don't have ruby-kafka or scram feature. Is it normal ? 

Thanks.

**Comment by dasch** [comment]
The bump to v3.8.0 was done _before_ merging SCRAM support.

I've just released version `0.4.0.beta1` – please try that out and report back if everything works.
