### ISSUE TITLE
Configuring logger in Racecar.configure block

### ISSUE THREAD

**Issue by JanaVPetrova** [zendesk/racecar#71]
Hello!

Thank you for developing Racecar, it is very useful for us. 
But when configuring it for one of our applications I faced the following:

```ruby
Racecar.configure do |config|
  config.brokers = [...]
  config.group_id = "my_shiny_group_id"
  config.logger = MyLogger.new # here is the problem
end
Racecar.logger = MyLogger.new # that's the solution
```

I couldn't configure the logger object inside the `configure` block. I had to set it separately from all other things. I looked into the code and found out that that's because of KingKonf, that does not allow "fancy structures" (like the logger instance, for example). I was wondering, is this by design or it could be fixed (I'm ready to make a PR)?

**Comment by dasch** [comment]
#72 should fix it.
