### ISSUE TITLE
Horizontally Scalable for Consumers?

### ISSUE THREAD

**Issue by allcentury** [zendesk/racecar#74]
I see in https://github.com/zendesk/ruby-kafka#consuming-messages-from-kafka that:

> Each consumer process will be assigned one or more partitions from each topic that the group subscribes to. In order to handle more messages, simply start more processes.

Is this true for racecar?  Can we simply add more boxes that run the `bundle exec racecar MyConsumer` and assuming we have the brokers/partitions configured it will scale?

I read through https://github.com/zendesk/ruby-kafka#consumer-design but I'm not sure if that covers it.

**Comment by mensfeld** [comment]
Long story short: yes. Racecar is based on ruby-kafka and  handles Kafka interactions in the same way.

**Comment by dasch** [comment]
What he said.
