### ISSUE TITLE
Thread deadlocks?

### ISSUE THREAD

**Issue by netik** [zendesk/racecar#83]
When running under ruby 2.4.4 (and any other ruby I tried, 2.3.7, others) and the ruby application spins up threads at application start, I have noticed that after awhile the threads that were created at startup eventually deadlock.

For example, our rails app opens a websocket. We read from Kafka and inject into the websocket using racecar.  This websocket has a thread on it that does ping/pongs to the server. The connection was constantly dropping because the ping/pong thread would fire a sleep() and seize up. 

This happens only when running with --daemonize. Running without it works fine. I suspect that somehow the forking process is interferring with the Thread, but I can't prove this yet. 

Any thoughts?

**Comment by dasch** [comment]
How you provide a minimal example of your code? It sounds like many things are in play. For example, `--daemonize` causes the process to fork, which can cause problems with open sockets. You may need to lazily open the websocket connection.
