### ISSUE TITLE
log writing failed. can't be called from trap context

### ISSUE THREAD

**Issue by GeminPatel** [zendesk/racecar#86]
When a racecar consumer is running and I send a SIGTERM to it. It prints the following:

Jun 11 18:55:49 ip-10-212-33-14 systemd[1]: Stopping App client consumer. Instance=1....
Jun 11 18:55:49 ip-10-212-33-14 bash[9370]: log writing failed. can't be called from trap context
Jun 11 18:55:49 ip-10-212-33-14 bash[9370]: log writing failed. can't be called from trap context
Jun 11 18:55:49 ip-10-212-33-14 bash[9370]: log writing failed. can't be called from trap context
Jun 11 18:55:49 ip-10-212-33-14 bash[9370]: log writing failed. can't be called from trap context
Jun 11 18:55:49 ip-10-212-33-14 bash[9370]: log writing failed. can't be called from trap context
Jun 11 18:55:49 ip-10-212-33-14 bash[9370]: log writing failed. can't be called from trap context
Jun 11 18:55:49 ip-10-212-33-14 systemd[1]: Stopped App client consumer. Instance=1..
Not always but sometimes.

I think this maybe because we can not use logger in signal handler https://bugs.ruby-lang.org/issues/7917, but ruby-kafka is doing this. If you follow trap signal handling by racecar you will finally land in a code in ruby-kafka that uses [logger.info
](https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/broker_pool.rb#L36)

Solution may be to create a new thread like karafka. But I don't like this method. 

Ruby-kafka ticket ref: https://github.com/zendesk/ruby-kafka/issues/598

Version of Ruby: 2.3.1
Version of Kafka: 0.11.0.1
Version of ruby-kafka: 0.5.2
Version of racecar: 0.3.7

**Comment by mensfeld** [comment]
I would advise to dirty hack it with a new thread upon  instrumentation and logging from trap the way it is done in Karafka: https://github.com/karafka/karafka/blob/1.3-wip/lib/karafka/status.rb#L24

Proven to work and much more friendly towards custom loggers and instrumentation than the async pipe solution.

**Comment by dasch** [comment]
@mensfeld would the signal handler be able to just spin up a new thread, call into ruby-kafka, then join the thread?

**Comment by mensfeld** [comment]
@dasch yes. It's not the most elegant but it is still way better than using IO.select and friends as it basically disallows user to add custom instrumentation. As long as you don't forget to `#join` the thread from within the trap context, it will work fine.
