### ISSUE TITLE
Connection error while fetching messages: Connection error Errno::EBADF: Bad file descriptor

### ISSUE THREAD

**Issue by GeminPatel** [zendesk/racecar#87]
Simply start a consumer. Lets say for the sake of simplicity that there is nothing to consume. When I shutdown a consumer I get the following error in my logs.

D, [2018-06-13T11:01:18.380510 #23536] DEBUG -- : Closing socket to x.x.x.x:9092
D, [2018-06-13T11:01:18.380584 #23536] DEBUG -- : Closing socket to x.x.x.x:9092
E, [2018-06-13T11:01:18.380668 #23536] ERROR -- : Connection error while fetching messages: Connection error Errno::EBADF: Bad file descriptor

Version of Ruby:2.3.1
Version of Kafka:0.5.2
Version of ruby-kafka:0.3.7

**Comment by dasch** [comment]
Is this causing a functional problem? We log all sorts of errors, but when shutting down you might get false positives due to the async nature of ruby-kafka.

**Comment by GeminPatel** [comment]
I dont think it is causing any functional issue. Will let you know if I find something
