### ISSUE TITLE
Replay from offset

### ISSUE THREAD

**Issue by allcentury** [zendesk/racecar#88]
Does racecar have an API to allow the consumer to seek from a specific offset?  There are times where we want to replay but right now I'm not seeing a way to do it.

**Comment by mensfeld** [comment]
Hey @allcentury it does not. Racecar aims to be a simple wrapping framework. You can easily fallback to the raw [ruby-kafka](https://github.com/zendesk/ruby-kafka), you can look at [karafka](https://github.com/karafka/karafka) that has this option or you can PR (always welcome) :)

**Comment by kishor557** [comment]
I have kept this in my consumer
  subscribes_to "requests_topic", start_from_beginning: false
When I restart my application, It is reading all the past messages again. Any help would be appreciated.
