### ISSUE TITLE
Different clusters for consumers

### ISSUE THREAD

**Issue by Jakanapes** [zendesk/racecar#92]
Is there support for having consumers read from different clusters?

Can the brokers be overridden in the consumer class?

**Comment by dasch** [comment]
Since each consumer runs in its own process, you can start each with a different set of brokers:

```sh
$ RACECAR_BROKERS=kafka1.cluster1,kafka2.cluster1 racecar --daemonize Cluster1Consumer
$ RACECAR_BROKERS=kafka1.cluster2,kafka2.cluster2 racecar --daemonize Cluster1Consumer
```
