### ISSUE TITLE
ServiceDiscovery.find ... is this another pretended class?

### ISSUE THREAD

**Issue by MadBomber** [zendesk/racecar#94]
I'm sorry if this is already something that you've addressed.  I started writing this issue before checking the closed issues.  I'm trying to checkout the current `racecar` gem in IRB using the code snippets in the README.md file.

The prospects of a `ServiceDiscovery.find` functionality are very appealing to me.  I was disappointed when your config example didn't work becase no such class exists.

**Comment by dasch** [comment]
There's no generic way of doing service discovery, you'll have to find something specific to your needs.
