### ISSUE TITLE
Slow startup troubleshooting

### ISSUE THREAD

**Issue by latortuga** [zendesk/racecar#95]
Hi there, thanks so much for this gem!

I'm having an issue where in my staging environment, racecar takes *forever* to start up. I see these lines:

```sh
=> Starting Racecar consumer DataSyncConsumer...
=> Detected Rails, booting application...
```

and then a LONG wait (7+ minutes) before I see the VROOOM message and messages start getting handled.

Some additional factors that might play into this:

- Behavior happens in staging where we are connecting to Kafka in confluent cloud
- I do not see it in development mode connecting to a local Kafka broker

Any chance you might have some insight as to what's taking my consumer so long to start up?

**Comment by dasch** [comment]
Do you have e.g. Datadog instrumentation set up? If that's the case, you can monitor the various API calls.

**Comment by dasch** [comment]
Otherwise, looking at the timestamps in the log (assuming you're running at DEBUG level) should help.

**Comment by latortuga** [comment]
I'm not sure how to troubleshoot this. Here's what I see:

```
Oct 17 12:10:53 mymachine1 systemd[1]: Started myapp-sync@5000.service.
Oct 17 12:10:54 mymachine1 myapp-sync@5000.service[7066]: => Starting Racecar consumer DataSyncConsumer...
Oct 17 12:10:54 mymachine1 myapp-sync@5000.service[7066]: => Detected Rails, booting application...
Oct 17 12:18:12 mymachine1 myapp-sync@5000.service[7066]: => Logging to /var/www/myapp/shared/log/racecar.log
Oct 17 12:18:12 mymachine1 myapp-sync@5000.service[7066]: => Wrooooom!
Oct 17 12:18:12 mymachine1 myapp-sync@5000.service[7066]: => Ctrl-C to shutdown consumer
```

Will Datadog help with this? Notice how there's more than 7 minutes between "Detected" and "Logging" lines. Again, this doesn't happen to me in development mode, and our app *certainly* does not take this long to boot up.

**Comment by dasch** [comment]
Closing due to a lack of activity – feel free to open a new issue if you still have this problem.

**Comment by latortuga** [comment]
@dasch I actually finally figured out what was going on with this. It wasn't racecar's fault, but by the same token it wasn't Kafka either. It turns out it was bootsnap that was taking forever to initialize the cache. The problem was that our capistrano deployment symlinks the bundler gem cache to each deploy but never cleans up old ruby versions - so my vendor/bundle/ruby directory had entries for numerous old rubies and bootsnap insisted on adding all of them to the load path. This takes a LONG time, especially when spinning up a new process on deploy.

So I guess technically I was wrong when I said "our app certainly does not take this long to boot up" - I guess it did!
